### ISSUE TITLE
zswag.gen: Allow specifying base64 encoding for URL parameter

### ISSUE THREAD

**Issue by manishtemkar** [Klebert-Engineering/zswag#69]
As per the documentation, to have base64 encoding, the format must be specified as "byte," "base64" or "base64url".
By default, zswag.gen does not support setting this format on the command line.

It would be nice to have the format element supported on the command line. Since Zserio is a binary format, it will always need base64 encoding.

**Comment by josephbirkner** [comment]
Thanks for reporting! Will work on it in the next release.

**Comment by josephbirkner** [comment]
After fixing this ticket, it should be possible to provide an NDS service OpenAPI YAML without editing the YAML at all (Only using zswag.gen). Solution looks as follows:

### Parameter, security and path tags

```
# Specify parameter name, location and format for a request object field (or the whole object via *)
-c [method:][field?name=...&location=[path|body|query|header]&format=[binary|base64|hex]]

# Specify a security scheme for the method, details must be provided in the base-config 
-c [method:][security=...]

# Specify a path for the method. The path might be extended for path-parameters where
# no path placeholder is provided.
-c [method:][path=...]
```

**Examples:**

* For `myMethod`, put the whole request blob into the a query *"data"* parameter as base64: `-c myMethod:*?name=data&location=query&format=base64`
* For `myMethod`, set the *"AwesomeAuth"* auth scheme: `-c myMethod:security=AwesomeAuth`
* For `myMethod`, provide the path and place `myField` explicitely: `-c myMethod:path=/my-method/{param},myField?name=param&location=path&format=string`

### Base Configuration File

```
-b|--base-config [yaml-file-path]
```

The YAML file must look as follows:

```yaml
# This is a sample zswag base-config YAML file.
# The method section can be used instead of `-c` tag arguments.
methods:
	*:
	- body
	myMethod:
	- path=/my-method/{param}
	- *?name=data&location=query&format=base64
	- myField?name=param&location=path&format=string

# Can be used to inject information directly into the respective OpenAPI sections.
securitySchemes: ...
info: ...
servers: ...
```
